if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    au VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'
Plug 'dylanaraps/wal.vim'
call plug#end()

set nocompatible
filetype plugin on
set encoding=utf-8
set laststatus=0
set viminfofile=NONE
set noswapfile
set incsearch
set hlsearch
set noshowcmd
set ignorecase
set clipboard=unnamedplus
set sts=2 sw=2 expandtab 
set wildmenu
set confirm
colorscheme wal
set background=dark
syntax on
nnoremap <C-s> :w!<CR>    
nnoremap <C-q> :q!<CR>    
nnoremap <silent> <C-x>    :so $MYVIMRC<cr>
nnoremap q :q<CR>

set fillchars+=eob:\ 
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

function Xclip() range
  call system('xclip -selection c,p', @r)
  echo line("'>") - line("'<") + 1 "lines yanked to clipboard" 
endfunction
vnoremap <C-y> "ry:call Xclip()  <cr>"


